name: Generate Snake Animation

on:
  schedule: # Jalankan otomatis setiap hari
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake SVG
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: DapCodes
          outputs: dist/snake.svg

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: snake
          path: dist/snake.svg

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generated snake animation"
          add: "dist/snake.svg"
